name: PublishCargoPio

on:
  workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      CRATE_NAME: cargo-pio
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Setup | Std
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default nightly
      - name: Setup | Default to nightly
        run: rustup default nightly
      - name: Login
        run: cargo login ${{ secrets.crates_io_token }}
      - name: Build | Publish
        run: cd ${{env.CRATE_NAME}}; cargo publish
      - name: Get the crate version from cargo
        run: |
          version=$(cargo metadata --format-version=1 --no-deps | jq -r ".packages[] | select(.name == \"${{env.CRATE_NAME}}\") | .version")
          echo "crate_version=$version" >> $GITHUB_ENV
          echo "${{env.CRATE_NAME}} version: $version"
      - name: Tag the new release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{env.CRATE_NAME}}-v${{env.crate_version}}
          message: "Release ${{env.CRATE_NAME}} v${{env.crate_version}}"
